export const studioModelConfigCopy: Record<string, string> = {
  'ModelConfig.profile.sectionTitle': 'Profile',
  'ModelConfig.profile.summaryLabel': 'AI Profile',
  'ModelConfig.profile.emptySummaryLabel': 'No profile applied',
  'ModelConfig.profile.applyButtonLabel': 'Apply profile',
  'ModelConfig.profile.changeButtonLabel': 'Change',
  'ModelConfig.profile.manageButtonTitle': 'Manage profiles',
  'ModelConfig.profile.modalTitle': 'Apply AI Profile',
  'ModelConfig.profile.modalHint': 'Choose an imported profile, preview the Studio AIConfig diff, then confirm.',
  'ModelConfig.profile.loadingLabel': 'Loading profiles...',
  'ModelConfig.profile.emptyLabel': 'No profiles available.',
  'ModelConfig.profile.currentBadgeLabel': 'Current',
  'ModelConfig.profile.cancelLabel': 'Cancel',
  'ModelConfig.profile.confirmLabel': 'Confirm & Apply',
  'ModelConfig.profile.applyingLabel': 'Applying...',
  'ModelConfig.profile.reloadLabel': 'Reload',
  'ModelConfig.profile.importLabel': 'Apply AI Profile',
  'ModelConfig.profile.previewTitle': 'Review changes',
  'ModelConfig.profile.previewHint': 'Review the before and after configuration. Nothing is saved until you confirm.',
  'ModelConfig.profile.previewingLabel': 'Computing preview...',
  'ModelConfig.profile.previewFirstApplyLabel': 'This scope has no AI configuration yet; applying this profile creates it.',
  'ModelConfig.profile.previewNoChangeLabel': 'This profile matches the current configuration. Applying it changes nothing.',
  'ModelConfig.profile.previewBeforeLabel': 'Current',
  'ModelConfig.profile.previewAfterLabel': 'After apply',
  'ModelConfig.profile.previewWarningsLabel': 'Warnings',
  'ModelConfig.profile.previewConfirmLabel': 'Confirm & Apply',
  'ModelConfig.profile.previewBackLabel': 'Back',
  'ModelConfig.section.chat.title': 'Text',
  'ModelConfig.section.tts.title': 'Text to speech',
  'ModelConfig.section.stt.title': 'Speech to text',
  'ModelConfig.section.image.title': 'Image',
  'ModelConfig.section.video.title': 'Video',
  'ModelConfig.section.voice.title': 'Voice',
  'ModelConfig.section.embed.title': 'Embeddings',
  'ModelConfig.section.world.title': 'World',
  'ModelConfig.capability.audioSynthesize.title': 'Text to speech',
  'ModelConfig.capability.audioSynthesize.subtitle': 'Generate speech audio from text',
  'ModelConfig.capability.audioSynthesize.detail': 'Routes owner-reviewed voice samples through the selected Runtime speech model.',
  'ModelConfig.capability.imageGenerate.title': 'Image generation',
  'ModelConfig.capability.imageGenerate.subtitle': 'Generate visual candidates from prompts',
  'ModelConfig.capability.imageGenerate.detail': 'Routes reference images and visual identity candidates through the selected Runtime image model.',
  'ModelConfig.capability.textGenerate.title': 'Text generation',
  'ModelConfig.capability.textGenerate.subtitle': 'Draft owner-reviewed text candidates',
  'ModelConfig.capability.textGenerate.detail': 'Routes seed drafts, settings proposals, and post copy assistance through the selected Runtime text model.',
  'ModelConfig.editor.common.timeoutLabel': 'Timeout',
  'ModelConfig.editor.common.defaultPlaceholder': 'Default',
  'ModelConfig.editor.common.previewBadgeLabel': 'Preview',
  'ModelConfig.editor.common.seedLabel': 'Seed',
  'ModelConfig.editor.common.seedHint': 'Leave empty to use the provider default.',
  'ModelConfig.editor.common.randomPlaceholder': 'Random',
  'ModelConfig.editor.common.noneLabel': 'None',
  'ModelConfig.editor.textGenerate.parametersLabel': 'Parameters',
  'ModelConfig.editor.textGenerate.generationDefaultsLabel': 'Generation defaults',
  'ModelConfig.editor.textGenerate.responseControlsLabel': 'Response controls',
  'ModelConfig.editor.textGenerate.advancedLabel': 'Advanced settings',
  'ModelConfig.editor.textGenerate.temperatureLabel': 'Temperature',
  'ModelConfig.editor.textGenerate.topPLabel': 'Top P',
  'ModelConfig.editor.textGenerate.topKLabel': 'Top K',
  'ModelConfig.editor.textGenerate.maxTokensLabel': 'Max tokens',
  'ModelConfig.editor.textGenerate.stopSequencesLabel': 'Stop sequences',
  'ModelConfig.editor.textGenerate.stopSequencesHint': 'Up to {{max}} sequences, one per line.',
  'ModelConfig.editor.textGenerate.stopSequencesPlaceholder': 'Type and press enter...',
  'ModelConfig.editor.textGenerate.presencePenaltyLabel': 'Presence penalty',
  'ModelConfig.editor.textGenerate.frequencyPenaltyLabel': 'Frequency penalty',
  'ModelConfig.editor.audioSynthesize.parametersLabel': 'Parameters',
  'ModelConfig.editor.audioSynthesize.voiceSectionLabel': 'Voice',
  'ModelConfig.editor.audioSynthesize.audioTuningSectionLabel': 'Audio tuning',
  'ModelConfig.editor.audioSynthesize.outputSectionLabel': 'Output',
  'ModelConfig.editor.audioSynthesize.voiceRefLabel': 'Voice reference',
  'ModelConfig.editor.audioSynthesize.voiceRefHint': 'Preset voice, custom voice asset, or provider voice reference.',
  'ModelConfig.editor.audioSynthesize.speakingRateLabel': 'Speaking rate',
  'ModelConfig.editor.audioSynthesize.volumeLabel': 'Volume',
  'ModelConfig.editor.audioSynthesize.pitchSemitonesLabel': 'Pitch',
  'ModelConfig.editor.audioSynthesize.languageHintLabel': 'Language hint',
  'ModelConfig.editor.audioSynthesize.languageHintHint': 'BCP-47 tag, e.g. en-US.',
  'ModelConfig.editor.audioSynthesize.responseFormatLabel': 'Response format',
  'ModelConfig.editor.image.companionModelsLabel': 'Companion models',
  'ModelConfig.editor.image.parametersLabel': 'Parameters',
  'ModelConfig.editor.image.sizeLabel': 'Size',
  'ModelConfig.editor.image.responseFormatLabel': 'Response format',
  'ModelConfig.editor.image.stepsLabel': 'Steps',
  'ModelConfig.editor.image.cfgScaleLabel': 'CFG scale',
  'ModelConfig.editor.image.samplerLabel': 'Sampler',
  'ModelConfig.editor.image.schedulerLabel': 'Scheduler',
  'ModelConfig.editor.image.customOptionsLabel': 'Custom options',
  'ModelConfig.editor.image.customOptionsHint': 'Advanced provider-specific options, one per line.',
  'ModelConfig.editor.image.oneOptionPerLinePlaceholder': 'key=value, one per line',
  'ModelConfig.hub.title': 'AI models',
  'ModelConfig.hub.backLabel': 'Back',
  'ModelConfig.hub.aggregateReady': '{{count}} ready',
  'ModelConfig.hub.aggregateAttention': '{{count}} need attention',
  'ModelConfig.hub.aggregateNeutral': '{{count}} unset',
  'ModelConfig.hub.aggregateEmpty': 'No capabilities configured',
  'ModelConfig.hub.detailTitleFormat': '{{section}} configuration',
  'ModelConfig.hub.activeModelLabel': 'Active model',
  'ModelConfig.hub.detailStatusReady': 'Runtime ready',
  'ModelConfig.hub.detailStatusAttention': 'Needs setup',
  'ModelConfig.hub.detailStatusNeutral': 'Not configured',
};

export function translateStudioModelConfigCopy(
  key: string,
  vars?: Readonly<Record<string, string | number | undefined>>,
): string {
  const defaultValue = typeof vars?.defaultValue === 'string' ? vars.defaultValue : undefined;
  const value = studioModelConfigCopy[key] || defaultValue || key;
  return Object.entries(vars ?? {}).reduce((current, [name, replacement]) => {
    if (name === 'defaultValue' || replacement === undefined) {
      return current;
    }
    return current.replaceAll(`{{${name}}}`, String(replacement));
  }, value);
}
